name: CMake Build Matrix

on:
  push:
  pull_request:
  release:

jobs:
  build-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: binaries-darwin
          path: build/rexsapi-darwin-1.0.0.zip

  build-more-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux
          path: build/rexsapi-linux-1.0.0.zip

  create_release:
    name: Create release
    if: startsWith( github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-stuff,build-more-stuff]
    steps:
      - uses: actions/checkout@v4
      - name: Display structure of downloaded files before download
        run: ls -R
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files after download
        run: ls -R
      - name: Create release
        id: create_release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          body: Some text
          prerelease: false
          draft: false
      - name: Upload release artifacts
        uses: pyTooling/Actions/releaser@r0
        with:
          tag: ${{ github.ref }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./artifacts/binaries-*/rexsapi-*.zip
