name: CMake Build Matrix

on:
  push:
  pull_request:
  release:

jobs:
  build-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: binaries-darwin
          path: build/rexsapi-darwin-1.0.0.zip

  build-more-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux
          path: build/rexsapi-linux-1.0.0.zip

  create_release:
    name: Create release
    if: startsWith( github.ref, 'refs/tags/') && endsWith(github.ref, '-latest')
    runs-on: ubuntu-latest
    needs: [build-stuff, build-more-stuff]
    steps:
      - uses: actions/checkout@v4
      - name: Display structure of folders
        run: ls -R
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: Some text
          artifacts: "./build/rexsapi-*.zip"
          removeArtifacts: true
