name: CMake Build Matrix

on:
  push:
  pull_request:
  release:

jobs:
  build-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: rexsapi-darwin-1.0.0.zip
          path: build/rexsapi-darwin-*.zip

  create_release:
    name: Create release
    if: startsWith( github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-stuff]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create release
        id: create_release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          body: Some text
          prerelease: false
          draft: false
      - name: Upload release artifacts
        uses: pyTooling/Actions/releaser@r0
        with:
          tag: ${{ github.ref }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: rexsapi-darwin-1.0.0.zip
