name: CMake Build Matrix

on:
  push:
  pull_request:
  release:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install mosquitto-clients
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '2.0'
          ports: '1883:1883'
          config: ${{ github.workspace }}/mosquitto.conf
          container-name: 'tochtli_test'
      - name: Test
        run: mosquitto_pub -h localhost -p 1883 -t hutzli -m "bah"
